
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fiscalhub_mabe
  username: root
  password: 123456
  port: 3306
  #host: 192.168.43.161
  host: 192.168.1.100

test:
  <<: *default
  database: imss_demo
  username: root
  password: TG2014
  port: 3306
  host: 65.181.125.83

production:
  <<: *default
  database: imss_demo
  username: root
  password: TG2014
  port: 3306
  host: localhost

