
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fiscalhub_mabe
  username: root
  password: 123456
  port: 3306
  host: 192.168.43.166

test:
  <<: *default
  database: fiscalhub_local
  username: root
  password: 123456
  port: 3306
  host: 192.168.1.100

production:
  <<: *default
  database: fiscalhub_local
  username: root
  password: 123456
  port: 3306
  host: 192.168.1.100
