
default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: fiscalhub_mabe
  username: root
  password: 123456
  port: 3306
  #host: 192.168.43.161
  host: 192.168.1.101

test:
  <<: *default
  database: imss_demo
  username: uruby
  password: RubyTe$ch2015
  port: 3306
  host: 52.20.128.239

production:
  <<: *default
  database: imss_demo
  username: uruby
  password: RubyTe$ch2015
  port: 3306
  host: 52.20.128.239


